### ISSUE TITLE
Remove section highlight for other pages

### ISSUE THREAD

**Issue by sps1112** [studiocentauri/studiocentauri.github.io#22]
**Problem**:- Sections on various other pages are being highlighted.

![7](https://user-images.githubusercontent.com/62471966/135084444-ff5f8b28-cae5-40c3-9c3f-339fc2f1c97b.PNG)

![8](https://user-images.githubusercontent.com/62471966/135084457-6f072ba2-1761-418c-b10f-edff26051563.PNG)

![10](https://user-images.githubusercontent.com/62471966/135084478-f2d6cdb9-541f-4cf0-84e7-feec08655c17.PNG)

**Issue with Problem**:- Unnecessary addition for other pages

**Current Solution (if any)**:- The highlight was added for the Home Page in #13 but was also transferred to other pages.

**Task**:- Remove the highlighting for all pages except the Home Page

**Note**:- Needs to be done for both PC and mobile. The highlighting should remain for Home Page

**Comment by rudranshg** [comment]
I am working on this issue.
