### ISSUE TITLE
Update NavBar for the website

### ISSUE THREAD

**Issue by sps1112** [studiocentauri/studiocentauri.github.io#34]
**Problem**:- Add some small changes to the NavBar

**Issue with Problem**:- Design consistency after the previous changes needs to be maintained

**Current Solution (if any)**:- Some changes added to the navbar as stated in #15 via #32 
- High Res

![1](https://user-images.githubusercontent.com/62471966/145799875-29a40372-30fb-4fc7-8cb3-c6d39097a4cb.PNG)
- Low Res

![3](https://user-images.githubusercontent.com/62471966/145799894-581fbfc5-1e57-44f6-91e8-7c5f60db4a2e.PNG)

**Task**:- A series of things need to be changed.
- Replace "GameDev_IITK" with "Game Development Society, IIT Kanpur"/ "GameDev Society, IITK"/ "Studio Centauri" 
  - Increase its Font Size
- Increase Resolution of Club Logo
- Increase size of logo in the case of lower res when opening the drop down menu
- Links on the left can be highlighted when hovered
- Increase left-right margin in case of the links (High res)

**Note**:- Other changes can be done as seen fit by the contributor

**Comment by Thisisakr47** [comment]
I'm working on this issue.
